services:
  workify-db:
    image: postgres:15
    container_name: postgres-db
    environment:
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      POSTGRES_DB: Workify
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  be-workify-app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: be-workify-app
    depends_on:
      - workify-db
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - DB_HOST=workify-db
      - SPRING_PROFILES_ACTIVE=prod

volumes:
  postgres_data:
